#!/bin/bash

sudo cp -a -v /etc/apt/sources.list /etc/apt/sources.list.0
printf "deb http://download.virtualbox.org/virtualbox/debian `lsb_release -c -s` contrib" | sudo tee -a /etc/apt/sources.list
sudo wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

sudo apt-get update
sudo apt-get -y install virtualbox-5.1
sudo apt-get -y install dkms
